### ISSUE TITLE
is this available yet for npm?

### ISSUE THREAD

**Issue by Allandy** [Your-Name-Here/Digitex-Node#8]

**Comment by Your-Name-Here** [comment]
Yes I had an issue with the first npm publish so I had to unpublish it and wait 24 hours. That time should have passed sometime today and it'll be available tonight/tomorrow.

**Comment by Your-Name-Here** [comment]
I'll reply here after I publish and test it.

**Comment by Your-Name-Here** [comment]
@Allandy It's been republished and can be included in your projects now using ``npm install digitex-node --save``
